version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - sockets:/app/tmp/sockets
      - public-data:/app/public
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: docker/nginx
    ports:
      - 80:80
    volumes:
      - sockets:/app/tmp/sockets
      - public-data:/app/public
    depends_on:
      - app
volumes:
  sockets:
  public-data:
  bundle:
  db-data:
